name: bloodcheck
description: "Demo Medical blood check app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.11
  http: ^1.1.0
  fl_chart: ^0.63.0
  font_awesome_flutter: ^10.5.0
  flutter_bloc: ^8.1.3
  qr_code_scanner: ^1.0.1
  logger: ^2.0.2

  firebase_core: ^2.24.2
  cupertino_icons: ^1.0.2
  firebase_messaging:
  firebase_analytics:
  flutter_foreground_task: ^6.1.0
  flutter_background: ^1.2.0
  auto_orientation: ^2.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/blood_icon_logo.png"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/blood_icon_logo.png