#version: '3.8'
#
#services:
#  bloodcheck:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_SECURITY_USER_NAME: "aes"
#      SPRING_SECURITY_USER_PASSWORD: "aes"
#    networks:
#      - bloodcheck-network
#
#networks:
#  bloodcheck-network:
#    driver: bridge